import { Customer, MenuItem, Order } from '@/types';

const now = new Date();

export const mockMenuItems: MenuItem[] = [
  {
    id: 'item-smash-burger',
    name: 'سمـاش برجر',
    category: 'Burgers',
    price: 3.800,
    isAvailable: true,
    prepTimeMinutes: 12,
  },
  {
    id: 'item-truffle-burger',
    name: 'ترافل مشروم برجر',
    category: 'Burgers',
    price: 4.600,
    isAvailable: true,
    prepTimeMinutes: 15,
  },
  {
    id: 'item-chicken-sando',
    name: 'كريسبي تشيكن',
    category: 'Sandwiches',
    price: 3.200,
    isAvailable: true,
    prepTimeMinutes: 11,
  },
  {
    id: 'item-loaded-fries',
    name: 'بطاطس لودد',
    category: 'Sides',
    price: 1.800,
    isAvailable: true,
    prepTimeMinutes: 8,
  },
  {
    id: 'item-caesar-salad',
    name: 'سلطة سيزر',
    category: 'Salads',
    price: 2.600,
    isAvailable: true,
    prepTimeMinutes: 9,
  },
  {
    id: 'item-spanish-latte',
    name: 'سبانيش لاتيه بارد',
    category: 'Beverages',
    price: 1.900,
    isAvailable: true,
    prepTimeMinutes: 4,
  },
  {
    id: 'item-orange-juice',
    name: 'عصير برتقال فريش',
    category: 'Beverages',
    price: 1.600,
    isAvailable: true,
    prepTimeMinutes: 3,
  },
  {
    id: 'item-lotus-cake',
    name: 'لوتس تشيز كيك',
    category: 'Desserts',
    price: 2.400,
    isAvailable: true,
    prepTimeMinutes: 6,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'customer-sara',
    fullName: 'سارة المطيري',
    phone: '+96895000001',
    totalSpend: 82.000,
    visitCount: 6,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 30).toISOString(),
    favoriteDish: 'سموكد بيف برجر',
  },
  {
    id: 'customer-ali',
    fullName: 'علي الشهري',
    phone: '+96895000002',
    totalSpend: 124.000,
    visitCount: 9,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 75).toISOString(),
    favoriteDish: 'اسبريسو دبل',
  },
  {
    id: 'customer-lina',
    fullName: 'لينا الحسن',
    phone: '+96895000003',
    totalSpend: 36.500,
    visitCount: 3,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 140).toISOString(),
    favoriteDish: 'سلطة سوبر فود',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-001',
    status: 'preparing',
    fulfillmentType: 'dine-in',
    tableNumber: 'A3',
    customer: mockCustomers[0],
    total: 7.500,
    items: [
      {
        id: 'order-001-item-1',
        menuItemId: 'item-smash-burger',
        name: 'سمـاش برجر',
        price: 3.800,
        quantity: 1,
      },
      {
        id: 'order-001-item-2',
        menuItemId: 'item-spanish-latte',
        name: 'سبانيش لاتيه بارد',
        price: 1.900,
        quantity: 1,
      },
      {
        id: 'order-001-item-3',
        menuItemId: 'item-loaded-fries',
        name: 'بطاطس لودد',
        price: 1.800,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 25).toISOString(),
    source: 'قاعة العائلات',
    prepTimeMinutes: 15,
  },
  {
    id: 'order-002',
    status: 'new',
    fulfillmentType: 'pickup',
    customer: mockCustomers[1],
    total: 6.200,
    items: [
      {
        id: 'order-002-item-1',
        menuItemId: 'item-truffle-burger',
        name: 'ترافل مشروم برجر',
        price: 4.600,
        quantity: 1,
      },
      {
        id: 'order-002-item-2',
        menuItemId: 'item-orange-juice',
        name: 'عصير برتقال فريش',
        price: 1.600,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 10).toISOString(),
    source: 'تطبيق المطعم',
  },
  {
    id: 'order-003',
    status: 'ready',
    fulfillmentType: 'dine-in',
    tableNumber: 'B2',
    customer: mockCustomers[2],
    total: 5.600,
    items: [
      {
        id: 'order-003-item-1',
        menuItemId: 'item-chicken-sando',
        name: 'كريسبي تشيكن',
        price: 3.200,
        quantity: 1,
      },
      {
        id: 'order-003-item-2',
        menuItemId: 'item-lotus-cake',
        name: 'لوتس تشيز كيك',
        price: 2.400,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 55).toISOString(),
    readyAt: new Date(now.getTime() - 1000 * 60 * 15).toISOString(),
    source: 'صالة الأفراد',
  },
];
