import { Customer, MenuItem, Order } from '@/types';

const now = new Date();

export const mockMenuItems: MenuItem[] = [
  {
    id: 'item-smash-burger',
    name: 'سمـاش برجر',
    category: 'Burgers',
    price: 38,
    isAvailable: true,
    prepTimeMinutes: 12,
  },
  {
    id: 'item-truffle-burger',
    name: 'ترافل مشروم برجر',
    category: 'Burgers',
    price: 46,
    isAvailable: true,
    prepTimeMinutes: 15,
  },
  {
    id: 'item-chicken-sando',
    name: 'كريسبي تشيكن',
    category: 'Sandwiches',
    price: 32,
    isAvailable: true,
    prepTimeMinutes: 11,
  },
  {
    id: 'item-loaded-fries',
    name: 'بطاطس لودد',
    category: 'Sides',
    price: 18,
    isAvailable: true,
    prepTimeMinutes: 8,
  },
  {
    id: 'item-caesar-salad',
    name: 'سلطة سيزر',
    category: 'Salads',
    price: 26,
    isAvailable: true,
    prepTimeMinutes: 9,
  },
  {
    id: 'item-spanish-latte',
    name: 'سبانيش لاتيه بارد',
    category: 'Beverages',
    price: 19,
    isAvailable: true,
    prepTimeMinutes: 4,
  },
  {
    id: 'item-orange-juice',
    name: 'عصير برتقال فريش',
    category: 'Beverages',
    price: 16,
    isAvailable: true,
    prepTimeMinutes: 3,
  },
  {
    id: 'item-lotus-cake',
    name: 'لوتس تشيز كيك',
    category: 'Desserts',
    price: 24,
    isAvailable: true,
    prepTimeMinutes: 6,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'customer-sara',
    fullName: 'سارة المطيري',
    phone: '+966500000001',
    totalSpend: 820,
    visitCount: 6,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 30).toISOString(),
    favoriteDish: 'سموكد بيف برجر',
  },
  {
    id: 'customer-ali',
    fullName: 'علي الشهري',
    phone: '+966500000002',
    totalSpend: 1240,
    visitCount: 9,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 75).toISOString(),
    favoriteDish: 'اسبريسو دبل',
  },
  {
    id: 'customer-lina',
    fullName: 'لينا الحسن',
    phone: '+966500000003',
    totalSpend: 365,
    visitCount: 3,
    lastOrderAt: new Date(now.getTime() - 1000 * 60 * 140).toISOString(),
    favoriteDish: 'سلطة سوبر فود',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'order-001',
    status: 'preparing',
    fulfillmentType: 'dine-in',
    tableNumber: 'A3',
    customer: mockCustomers[0],
    total: 75,
    items: [
      {
        id: 'order-001-item-1',
        menuItemId: 'item-smash-burger',
        name: 'سمـاش برجر',
        price: 38,
        quantity: 1,
      },
      {
        id: 'order-001-item-2',
        menuItemId: 'item-spanish-latte',
        name: 'سبانيش لاتيه بارد',
        price: 19,
        quantity: 1,
      },
      {
        id: 'order-001-item-3',
        menuItemId: 'item-loaded-fries',
        name: 'بطاطس لودد',
        price: 18,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 25).toISOString(),
    source: 'قاعة العائلات',
    prepTimeMinutes: 15,
  },
  {
    id: 'order-002',
    status: 'new',
    fulfillmentType: 'pickup',
    customer: mockCustomers[1],
    total: 62,
    items: [
      {
        id: 'order-002-item-1',
        menuItemId: 'item-truffle-burger',
        name: 'ترافل مشروم برجر',
        price: 46,
        quantity: 1,
      },
      {
        id: 'order-002-item-2',
        menuItemId: 'item-orange-juice',
        name: 'عصير برتقال فريش',
        price: 16,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 10).toISOString(),
    source: 'تطبيق المطعم',
  },
  {
    id: 'order-003',
    status: 'ready',
    fulfillmentType: 'dine-in',
    tableNumber: 'B2',
    customer: mockCustomers[2],
    total: 56,
    items: [
      {
        id: 'order-003-item-1',
        menuItemId: 'item-chicken-sando',
        name: 'كريسبي تشيكن',
        price: 32,
        quantity: 1,
      },
      {
        id: 'order-003-item-2',
        menuItemId: 'item-lotus-cake',
        name: 'لوتس تشيز كيك',
        price: 24,
        quantity: 1,
      },
    ],
    createdAt: new Date(now.getTime() - 1000 * 60 * 55).toISOString(),
    readyAt: new Date(now.getTime() - 1000 * 60 * 15).toISOString(),
    source: 'صالة الأفراد',
  },
];
